# Generated by Django 4.2 on 2023-05-04 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchwhat_app', '0002_streamplatform_watchwhat_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchwhat',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Watchwhat', to='watchwhat_app.streamplatform'),
        ),
    ]
