# Generated by Django 4.2 on 2023-05-04 09:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('watchwhat_app', '0003_watchwhat_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchwhat',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Watchwhat', to='watchwhat_app.streamplatform'),
            preserve_default=False,
        ),
    ]
