# Generated by Django 4.2 on 2023-05-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchwhat_app', '0005_alter_watchwhat_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchwhat',
            name='platform',
        ),
    ]
