# Generated by Django 4.2 on 2023-05-05 07:11

from django.db import migrations, models
import django.db.models.deletion
import watchwhat_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('watchwhat_app', '0007_watchwhat_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('watchwhat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='watchwhat_app.watchwhat')),
            ],
        ),
    ]
